#!/bin/bash
if [ $# -ne 2 ];
then echo "Syntax: ban <IP-mask> <comment>"; exit; fi
if [[ "$1" == *:* ]] ; then iptables=ip6tables ; else iptables=iptables ; fi
$iptables -D INPUT -s "$1" -j DROP -m comment --comment "$2" 2> /dev/null
$iptables -A INPUT -s "$1" -j DROP -m comment --comment "$2"
