#!/usr/bin/env bash
set -eu

if [[ $# -eq 0 ]]
then
	echo 'Usage: delink LINK...' 1>&2
	exit 1
fi

tmpext=.delink-$(date +%s)

for f in "$@"
do
	cp --archive --dereference "$f" "$f$tmpext"
	rm "$f"
	mv "$f$tmpext" "$f"
done
