#!/usr/bin/env bash
# Create directory by current date (prefixing a letter as needed)
set -eu

date=$(date -Idate)
dir=$date
letters=abcdefghijklmnopqrstuvwxyz

while [[ -e "$dir" ]]
do
	letters=${letters:1}
	dir=$date${letters:0:1}
done

mkdir "$dir"
echo "$dir"
cd "$dir"
