#!/bin/bash
# Create directory by current date (prefixing a letter as needed)
set -eu
DATE=`date -Idate`
DIR=$DATE
LETTERS=abcdefghijklmnopqrstuvwxyz
while [ -e $DIR ];
do
	LETTERS=${LETTERS:1}
	DIR=$DATE${LETTERS:0:1}
done
mkdir $DIR
echo $DIR
cd $DIR
