#!/bin/bash
if [ $# -ne 2 ];
then echo "Syntax: unban <IP-mask> <comment>"; exit; fi
if [[ "$1" == *:* ]] ; then iptables=ip6tables ; else iptables=iptables ; fi
$iptables -D INPUT -s $1 -j DROP -m comment --comment "$2"
